# Generated by Django 5.1.5 on 2025-02-13 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("productName", models.CharField(max_length=255)),
                ("productDescription", models.TextField(blank=True, null=True)),
                ("productType", models.CharField(max_length=255)),
                ("productQuantity", models.IntegerField(default=0)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255, null=True)),
                ("phoneNumber", models.CharField(max_length=255, null=True)),
                ("region", models.CharField(max_length=255, null=True)),
                ("address", models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SupplierOrders",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("supplierId", models.CharField(max_length=255)),
                ("productId", models.CharField(max_length=255)),
                ("productAmount", models.IntegerField()),
                ("deliveryStatus", models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
